sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1.402
solution: IdentityServer4.Contrib.AspNetCore.Testing.sln

addons:
  apt:
    update: true

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
      name: dotnet-build
      if: tag IS NOT present
      script:
        - dotnet build
    - stage: test
      name: dotnet-test
      before_script:
        - sudo apt-get update && sudo apt-get install curl -y
      script:
        - ./test.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$IDENTITYSERVER_NUGET_APIKEY" "$TRAVIS_TAG"

