sudo: required
dist: bionic
language: csharp
solution: IdentityServer4.Contrib.Caching
mono: none
dotnet: 3.1.300
stages:
  - build
  - test
  - publish
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      script: ./run-tests.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$IDENTITYSERVER_NUGET_APIKEY" "$TRAVIS_TAG"

